#!/usr/bin/env bash

#
# Copyright (C) 2025 Luna <luna.realm.io.bennett24@outlook.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#!/usr/bin/env bash

# Don't change anything in the auto-generated XMLs.

# Ensure the target directory exists
mkdir -p "$PRODUCT_DIR/etc/sysconfig"

# Touch NULL configs.
for useless_product_sysconfigs in 'pixel_2019_exclusive.xml' 'pixel_experience_2019_midyear.xml' 'pixel_experience_2020.xml' 'pixel_experience_2020_midyear.xml' 'pixel_experience_2021.xml' 'pixel_experience_2021_midyear.xml' 'pixel_experience_2022.xml' 'pixel_experience_2023.xml' 'pixel_experience_2023_midyear.xml'; do
    touch $PRODUCT_DIR/etc/sysconfig/$useless_product_sysconfigs
done

# Also create the new file to mark it as edited.
touch $PRODUCT_DIR/etc/sysconfig/pixel_experience_2024.xml

cat >> $PRODUCT_DIR/etc/sysconfig/pixel_2016_exclusive.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
	<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
	<!-- These are configurations that should exist on Google's 2016 Pixel devices. -->
	<config>
		<!-- Both versions of this string are needed due to a miscommunication. b/29978934 -->
		<feature name="com.google.android.apps.photos.NEXUS_PRELOAD" />
		<feature name="com.google.android.apps.photos.nexus_preload" />
	</config>
	<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
EOF

cat >> $PRODUCT_DIR/etc/sysconfig/pixel_2017_exclusive.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
<!-- These are configurations that should exist on Google's 2017 and newer Nexus devices. -->
<config>
    <!-- This is meant to be the canonical feature identifying 2017 and newer Nexus devices. -->
    <feature name="com.google.android.feature.PIXEL_2017_EXPERIENCE" />

    <!--
       This is the canonical feature identifying devices which bundle Google Fi support. The
       Fi app and associated apps will be bundled (but may be disabled until a matching SIM
       is inserted).
       This feature may not be present before Android S.
    -->
    <feature name="com.google.android.feature.GOOGLE_FI_BUNDLED" />

    <!-- Allow SCONE JobIntentService & Services to run in background -->
    <allow-in-power-save package="com.google.android.apps.scone" />

    <!-- Allow Flipendo in power save. Will be present on pre-2020 devices for dogfooding. -->
    <allow-in-power-save-except-idle package="com.google.android.flipendo" />

    <!-- Allow Better Bug to take bug report. -->
    <bugreport-whitelisted package="com.google.android.apps.betterbug" />
    <bugreport-whitelisted package="com.google.android.apps.internal.betterbug" />
    <bugreport-whitelisted package="com.google.android.apps.betterbug.partners" />

    <!-- Allow Pixel modem service to run in background -->
    <allow-in-power-save package="com.google.modemservice" />

    <!-- Allow MDS ExperimentService to run in background -->
    <allow-in-power-save package="com.google.mds" />

    <!-- Allow Exo services to run in background -->
    <allow-in-power-save package="com.google.pixel.exo" />
    <allow-in-power-save package="com.google.ambient.streaming" />

    <!-- Allow OMA DM to run in background -->
    <allow-in-power-save package="com.android.omadm.service" />
    <allow-in-power-save package="com.android.sdm.plugins.connmo" />
    <allow-in-power-save package="com.android.sdm.plugins.dcmo" />
    <allow-in-power-save package="com.android.sdm.plugins.diagmon" />
    <allow-in-power-save package="com.android.vzwomatrigger" />
    <allow-in-power-save package="com.android.sdm.plugins.usccdm" />

    <!-- Allow Gate runners to run in background -->
    <allow-in-power-save package="com.google.pixel.gate.android.pysupport" />
    <allow-in-power-save package="com.google.pixel.gate.android.daemon" />

    <!-- Hide DocumentsUi Launcher/Downloads intent handling. DocumentsUi
         PrebootReceiver does not properly hide the launcher in work profile,
         so we need to include this as well. -->
    <component-override package="com.google.android.documentsui" >
        <component class="com.android.documentsui.LauncherActivity" enabled="false" />
        <component class="com.android.documentsui.ViewDownloadsActivity" enabled="false" />
    </component-override>

    <!-- ACTION_MANAGE_STORAGE handled by Files by Google -->
    <component-override package="com.google.android.storagemanager" >
        <component class="com.android.storagemanager.deletionhelper.DeletionHelperActivity" enabled="false" />
    </component-override>

    <!-- Make sure photos/video previews are handled by Photos. -->
    <component-override package="com.google.android.apps.nbu.files" >
        <component class="com.google.android.apps.nbu.files.gateway.preview.PreviewActivity" enabled="false" />
    </component-override>

    <component-override package="com.android.settings" >
        <!-- Display regulatory info in settings. -->
        <component class=".RegulatoryInfoDisplayActivity" enabled="true" />
    </component-override>

    <!-- Feature flag on RVC builds for AER requirements, b/159247801 -->
    <feature name="com.google.android.feature.AER_OPTIMIZED" />
</config>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
EOF

cat >> $PRODUCT_DIR/etc/sysconfig/pixel_2018_exclusive.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
<!-- These are configurations that should exist on Google's 2018 and newer Pixel devices. -->
<config>
    <!-- Allow Pixel modem service in background -->
    <allow-in-power-save package="com.google.modemservice" />

    <!-- Allow PixelLogger LoggingService to run in background -->
    <allow-in-power-save package="com.android.pixellogger" />

    <!-- Allow Pixel Logger to take bug report. -->
    <bugreport-whitelisted package="com.android.pixellogger" />

    <!-- Allow Flipendo in power save. Will be present on pre-2020 devices for dogfooding. -->
    <allow-in-power-save-except-idle package="com.google.android.flipendo" />

    <!-- The AI services open-source network component can bind to the odad package. -->
    <allow-association target="com.google.android.as.oss" allowed="com.google.android.odad" />

    <!-- The odad package can only bind to the AI services open-source network component. -->
    <allow-association target="com.google.android.odad" allowed="com.google.android.as.oss" />

    <!-- This is meant to be the canonical feature identifying 2018 and newer Pixel devices. -->
    <feature name="com.google.android.feature.PIXEL_2018_EXPERIENCE" />
</config>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
EOF

cat >> $PRODUCT_DIR/etc/sysconfig/pixel_experience_2019.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
<!-- These are configurations that should exist on Google's 2019 and newer devices. -->
<config>
    <!-- This is meant to be the canonical feature identifying 2019 and newer devices. -->
    <feature name="com.google.android.feature.PIXEL_2019_EXPERIENCE" />

    <!-- Allow Flipendo in power save. Will be present on pre-2020 devices for dogfooding. -->
    <allow-in-power-save-except-idle package="com.google.android.flipendo" />
</config>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
EOF

cat >> $PRODUCT_DIR/etc/sysconfig/pixel_experience_horizoncore.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
<!-- These are configurations that should exist on all Horizon devices. -->
<config>
    <!-- This is meant to be the canonical feature identifying 2016 and newer Nexus devices. -->
    <feature name="com.google.android.feature.PIXEL_EXPERIENCE" />

    <!-- google KidsHome feature -->
    <!-- <feature name="com.google.android.feature.KIDS_HOME_EXPERIENCE" /> -->

    <!-- Starting from Android R and above, the device with the system feature included would get Dialer call recording. -->
    <feature name="com.google.android.apps.dialer.call_recording_audio" />

    <!-- <feature name="com.google.android.feature.PREMIER_TIER" /> -->

    <system-user-whitelisted-app package="com.google.android.tts" />

    <!-- TODO: This is a temporary workaround for allowing GmsCore to receive this broadcast.
         This can be removed once OneTimeInitializer functionality is moved to GmsCore. -->
    <!-- <allow-implicit-broadcast action="com.google.android.onetimeinitializer.ONE_TIME_INITIALIZED" /> -->

    <!-- <feature name="com.google.android.feature.EEA_DEVICE" /> -->
    <!-- <feature name="com.google.android.feature.EEA_V2_DEVICE" /> -->
    <!-- <feature name="com.google.android.paid.search" /> -->
    <!-- <feature name="com.google.android.paid.chrome" /> -->
    <!-- <feature name="com.google.android.feature.ASI_PIXEL6" /> -->
</config>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/add_unlimited_backups.sh -->
EOF