cat >> $HORIZON_SYSTEM_DIR/etc/permissions/privapp-permissions-horizonux.screen.resolution.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- autogenerated by ./misc/scripts/rom_modifier_scripts/resolution_app_permissions_xml_conf.sh -->
<privapp-permissions xmlns:android="http://schemas.android.com/apk/res/android">
    <permission android:name="android.permission.WRITE_SECURE_SETTINGS" />
    
    <package android:name="horizonux.screen.resolution">
        <permission android:name="android.permission.WRITE_SECURE_SETTINGS" />
    </package>
</privapp-permissions>
<!-- autogenerated by ./misc/scripts/rom_modifier_scripts/resolution_app_permissions_xml_conf.sh -->
EOF